sudo: required
services:
  - docker

before_install: 
  - docker build -t miggulondon/project-generation -f Dockerfile.dev . 

script:
  - docker run -e CI=true miggulondon/project-generation yarn test