sudo: required
services:
  - docker

before_install: 
  - docker build -t miggulondon/project-generation -f Dockerfile.dev . 

script:
  - docker run -e CI=true miggulondon/project-generation yarn test

deploy:
  provider: elasticbeanstalk
  edge: "true"
  region: "us-east-1"
  app: "Project Generation"
  env: "Project-generation-env"
  bucket_name: "elasticbeanstalk-us-east-1-244542120433"
  bucket_path: "docker-react"
  on:
    branch: main
  access-key-id: $AWS_ACCESS_KEY
  secret-access-key: $AWS_SECRET_KEY
